spring:
  application:
    name: exercises

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: /


dl:
  kafka:
    region: us-east-1
    env: dev
    domain: crm
    version: v1

kafka:
  bootstrap:
    servers: localhost:9092